import Head from 'next/head'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
export default function Pricing() {
  return (
<div>
<Head>
    <title>Pricing & Benefits</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/Images/favicon.ico" />
    <link rel="stylesheet" href="codecarbine.css" />
    <link rel="stylesheet" href="custom-style.css" />
    <script src="https://cdn.lordicon.com/xdjxvujz.js"></script>
</Head>
<NavBar />
<section id="pricing" className="text-gray-400 bg-gray-900 body-font overflow-hidden ">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">Pricing</p>
            <h1 className="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Pricing Plans</h1>
            <div className="w-32 h-1 bg-purple-500 rounded mx-auto my-1" />
            {/* **__MONTHLY ANNUALLY BUTTON__** <div class="flex mx-auto border-2 border-purple-600 rounded overflow-hidden mt-6"><button class="py-1 px-4 bg-purple-600 text-white focus:outline-none">Monthly</button><button class="py-1 px-4 focus:outline-none">Annually</button></div>*/}
          </div>
          <div className="flex flex-wrap -m-4 justify-center">
            <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
              <div className="h-full p-6 bg-gray-700 bg-opacity-40 shadow-lg flex flex-col relative overflow-hidden rounded-lg">
                <h2 className="text-sm tracking-widest title-font mb-1 font-medium">DISCORD SERVER SETUP</h2>
                <h1 className="text-5xl text-gray-100 leading-none flex items-center pb-4 mb-4 border-b border-gray-200"><span>$50</span></h1>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Custom theme, color, & roles of your choice.
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Welcome screen
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Verification system
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Moderation bots
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-6">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" /> 
                    </svg>
                  </span>
                  Ticket raising system
                </p>
                <a href="https://forms.gle/t3TK53wsgQyTEdfb6" rel="noopener noreferrer" target="_blank" className="flex items-center mt-auto text-white text-center font-bold bg-purple-600 border-2 border-purple-600 border-opacity-0 py-2 px-4 tracking-wider text-base hover:border-opacity-100 hover:text-purple-600 hover:bg-transparent rounded-full duration-300 ease-in-out">Choose plan</a><a href="https://www.fiverr.com/share/Dogvqy" className="text-2xs text-center tracking-wider text-gray-400 mt-3">*Click to compare pricing of this service.</a>
              </div>
            </div>
            <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
              <div className="h-full p-6 bg-gray-700 bg-opacity-60 shadow-lg flex flex-col relative overflow-hidden rounded">
                <span className="bg-purple-600 text-white px-3 py-1 tracking-widest text-xs absolute right-0 top-0 rounded-bl">POPULAR</span>
                <h2 className="text-sm tracking-widest title-font mb-1 font-medium">FULL WEBSITE CREATION</h2>
                <h1 className="text-5xl text-gray-100 leading-none flex items-center pb-4 mb-4 border-b border-gray-200"><span>$95<sup className="ml-4 mb-4 line-through text-gray-400 text-lg">$250</sup></span></h1>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Responsive Design
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Social media integration
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Content Upload
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Source Code (Premium)
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-6">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Portfolio/StartUp Website
                </p>
                <a href="https://forms.gle/t3TK53wsgQyTEdfb6" rel="noopener noreferrer" target="_blank" className="flex items-center mt-auto text-white text-center font-bold bg-purple-600 border-2 border-purple-600 border-opacity-0 py-2 px-4 tracking-wider text-base hover:border-opacity-100 hover:text-purple-600 hover:bg-transparent rounded-full duration-300 ease-in-out">Choose plan</a><a href="https://www.fiverr.com/share/jRVzl7" className="text-2xs text-center tracking-wider text-gray-400 mt-3">*Click to compare pricing of this service.</a>
              </div>
            </div>
            <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
              <div className="h-full p-6 bg-gray-700 bg-opacity-40 shadow-lg flex flex-col relative overflow-hidden rounded-lg">
                <h2 className="text-sm tracking-widest title-font mb-1 font-medium">CREATIVE DESIGNING</h2>
                <h1 className="text-5xl text-gray-100 leading-none flex items-center pb-4 mb-4 border-b border-gray-200"><span>$75</span></h1>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  UI Design using Figma
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Create Banners<span className="font-bold mx-1 text-base">∀</span> topics
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Make business cards
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Unique designs
                </p>
                <p className="flex items-center text-sm pop-semi text-gray-300 mb-6">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-purple-600 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5" />
                    </svg>
                  </span>
                  Make NFT Collection
                </p>
                <a href="https://forms.gle/t3TK53wsgQyTEdfb6" rel="noopener noreferrer" target="_blank" className="flex items-center mt-auto text-white text-center font-bold bg-purple-600 border-2 border-purple-600 border-opacity-0 py-2 px-4 tracking-wider text-base hover:border-opacity-100 hover:text-purple-600 hover:bg-transparent rounded-full duration-300 ease-in-out">Choose plan</a><a href="https://www.fiverr.com/share/p0oQXR" className="text-2xs text-center tracking-wider text-gray-400 mt-3">*Click to compare pricing of these services.</a>
              </div>
            </div>
          </div>
        </div>
      </section>
<section  className="text-gray-400 bg-gray-900 body-font overflow-hidden">
      <div className="flex flex-col text-center w-full mb-20">
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">Why choose me?</p>
            <h1 className="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Benefits you'll get</h1>
            <div className="w-32 h-1 bg-purple-500 rounded mx-auto my-1" />
            {/* **__MONTHLY ANNUALLY BUTTON__** <div class="flex mx-auto border-2 border-purple-600 rounded overflow-hidden mt-6"><button class="py-1 px-4 bg-purple-600 text-white focus:outline-none">Monthly</button><button class="py-1 px-4 focus:outline-none">Annually</button></div>*/}
            <section className="text-gray-400 bg-gray-900 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <h3 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">Flexible schedule & plan making
                <br className="hidden lg:inline-block"/>
              </h3>
              <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
              <div className="flex justify-center">
                {/* <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">Button</button>
                <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button> */}
              </div>
            </div>
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
              <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
            </div>
          </div>
        </section>
        <section className="text-gray-400 bg-gray-900 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
              <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
            </div>
            <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
              <h3 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">Timely completions
                <br className="hidden lg:inline-block"/>
              </h3>
              <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
              <div className="flex justify-center">
                {/* <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">Button</button>
                <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button> */}
              </div>
            </div>
          </div>
        </section>
        <section className="text-gray-400 bg-gray-900 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <h3 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">Quick response to queries
                <br className="hidden lg:inline-block"/>
              </h3>
              <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
              <div className="flex justify-center">
                {/* <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">Button</button>
                <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button> */}
              </div>
            </div>
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
              <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
            </div>
          </div>
        </section>
        <section className="text-gray-400 bg-gray-900 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
              <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
            </div>
            <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
              <h3 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">Consistent with the work
                <br className="hidden lg:inline-block"/>
              </h3>
              <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
              <div className="flex justify-center">
                {/* <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">Button</button>
                <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button> */}
              </div>
            </div>
          </div>
        </section>
        <section className="text-gray-400 bg-gray-900 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <h3 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">Rectification & maintenance of project
                <br className="hidden lg:inline-block"/>
              </h3>
              <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
              <div className="flex justify-center">
                {/* <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">Button</button>
                <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button> */}
              </div>
            </div>
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
              <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
            </div>
          </div>
        </section>
        <section className="text-gray-400 bg-gray-900 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
              <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
            </div>
            <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
              <h3 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">Proper guidance
                <br className="hidden lg:inline-block"/>
              </h3>
              <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
              <div className="flex justify-center">
                {/* <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">Button</button>
                <button className="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button> */}
              </div>
            </div>
          </div>
        </section>  
          </div>
          </section>
       <Footer />
     </div>
  )
}
